# Site settings
name: bigdatajava博客
email: bigdatajava@163.com
author: 刘文超
url: http://www.XXX.com
resume_site: http://www.XXX.com/
github: https://github.com/bigdatajava/
baseurl: "/blogspot"
description: 实践出真理!
meta_description: 刘文超;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bigdatajava

# Build settings
markdown: kramdown

